### PR TITLE
Fix for non-default mp_maxrounds

### PR DESCRIPTION
**Pull request by sapphyrus**
Didn't test this + won't work for overtime, but better than nothing
https://github.com/TrevenT/CSGOPanorama/blob/1ea836b5b28e9c43e7971df3ee3db41d20506e0f/panorama/panorama/scripts/scoreboard.js#L2825-L2846

### CODE REVIEW

**Comment by yuv41** [comment]
The original plugin doesn't care for maxrounds(?) I don't see the point of this 

Edit: Oh you mean for servers that their half time is not round 15 
Edit 2: I think there's a better way to do this I'll look into this later today, thanks for contributing! :)

**Comment by yuv41** [comment]
@sapphyrus , Implemented a fix for any amount of max rounds. (and will work on OT)

**Comment by sapphyrus** [comment]
should probably use `mp_halftime_duration` instead of hardcoded 15.0, but that seems a lot cleaner, good job

**Comment by yuv41** [comment]
> should probably use `mp_halftime_duration` instead of hardcoded 15.0, but that seems a lot cleaner, good job

mp_halftime_duration is the duration of the screen, it wouldn't affect the afterwards round start (I think)
The event i hooked is fired right when the halftime screen is showing up, by default its 15 seconds.
servers lower it a bit i think so it fits the timing i think.
Feel free to improve :D

**Pull request closed without merging**
